name: Add Version Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version from file
        id: version
        run: echo ::set-output name=version::$(grep -oP "(?<=s:language_server_version = ')[^']+" autoload/codeium/server.vim)
      - name: Check if tag exists
        id: add_tag
        run: |
          if git rev-parse ${{ steps.version.outputs.version }} >/dev/null 2>&1; then
            echo "Tag already exists"
            exit 0
          else
            echo "Tag doesn't exist"
            git tag ${{ steps.version.outputs.version }} && git push origin ${{ steps.version.outputs.version }}
          fi
        shell: bash
